### ISSUE TITLE
How to modify prometheus.yml

### ISSUE THREAD

**Issue by vsinha** [infinityworksltd/prom-conf#4]
I've deployed the prometheus stack in rancher. I'm wondering if there's a 'right way' to modify the `prometheus.yml` given that it's being mounted from inside the prom-conf container rather than as a static file. I'm looking to add another scrape job

Any help would be great!

**Comment by Rucknar** [comment]
@vsinha Apologies for losing track of this one. The prometheus config in the catalog is meant as starting place. You could choose to either map in your own config (removing the need for the sidekick) or you could fork the repository and update the config yourself. Totally up to you, a mount is probably easiest but might tie you down to specific host.
